---
abstract: '[DEPRECATED] Perl access to Oracle databases for old oraperl scripts'
author:
  - 'Tim Bunce <timb@cpan.org>'
  - 'John Scoles'
  - 'Yanick Champoux <yanick@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::More: 0.88
  warnings: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Oraperl
provides:
  Oraperl:
    file: lib/Oraperl.pm
    version: 1.51
requires:
  DBD::Oracle: 0
  DBI: 1.22
  Exporter: 0
  perl: 5.004
  sigtrap: 0
  strict: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Oraperl
  homepage: http://search.cpan.org/dist/Oraperl/
  repository: https://github.com/pythian/Oraperl.git
version: 1.51
x_authority: cpan:PYTHIAN
